### ISSUE TITLE
add sensor attributes for meter reading to support energy board

### ISSUE THREAD

**Issue by andremieth** [DominikWrobel/SmartWB#1]
Hi, thanks for this great integration!
Could you maybe add the missing sensor attributes in meter reading to support this in the energy dashboard?
I guess the two missing attributes should be ([documentation](https://www.home-assistant.io/docs/energy/faq/#resolution)):

- device_class: energy
- state_class: total

thanks!

**Comment by DominikWrobel** [comment]
Added to the v1.0 release,

If you like my work you can support me via:

<figure class="wp-block-image size-large"><a href="https://www.buymeacoffee.com/dominikjwrc"><img src="https://homeassistantwithoutaplan.files.wordpress.com/2023/07/coffe-3.png?w=182" alt="" class="wp-image-64"/></a></figure>
